import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

import './globals.css'
import { Header } from '@/components/layout/Header'
import { AuthProvider } from '@/provider/AuthProvider'

import type { Metadata } from 'next'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-full flex-col antialiased`}
      >
        <AuthProvider>
          <Header />
          <Toaster position="top-right" reverseOrder={false} />
          <main className="grow">{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
